version: '2'

services:
  party-0:
    hostname: party-0
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    networks:
      mpc_net:
        ipv4_address: 192.168.1.11
    ports:
      - "22"
  party-1:
    hostname: party-1
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    networks:
      mpc_net:
        ipv4_address: 192.168.1.12
    ports:
      - "22"
  party-2:
    hostname: party-2
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    networks:
      mpc_net:
        ipv4_address: 192.168.1.13
    ports:
      - "22"

networks:
  mpc_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
