# Dockerfile based on: https://github.com/oweidner/docker.openmpi/blob/master/Dockerfile
# https://codeburst.io/direct-connection-to-a-docker-container-with-ssh-56e1d2744ee5
# Build this image: docker build -t mpc .

FROM ubuntu:20.04

MAINTAINER Pierre-Francois Wolfe <pwolfe@bu.edu>

ENV USER mpc

ENV HOME=/home/${USER}

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && \
    apt-get install -y --no-install-recommends sudo apt-utils && \
    apt-get install -y --no-install-recommends openssh-server \
    make ssh gcc libopenmpi-dev openmpi-bin libsodium23 libsodium-dev && \
    apt clean && \
    apt purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /var/run/sshd
RUN echo 'root:${USER}' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

RUN useradd -ms /bin/bash mpc

# ------------------------------------------------------------
# Set-Up SSH with our Github deploy key
# ------------------------------------------------------------

ENV SSHDIR ${HOME}/.ssh/

RUN mkdir -p ${SSHDIR}

RUN ssh-keygen -A

ADD ssh/config ${SSHDIR}/config
ADD ssh/id_rsa.mpi ${SSHDIR}/id_rsa
ADD ssh/id_rsa.mpi.pub ${SSHDIR}/id_rsa.pub
ADD ssh/id_rsa.mpi.pub ${SSHDIR}/authorized_keys

RUN chmod -R 600 ${SSHDIR}* && \
    chown -R ${USER}:${USER} ${SSHDIR}

COPY src/* /home/${USER}/src/
COPY experiments/* /home/${USER}/experiments/
COPY tests/* /home/${USER}/tests/
COPY launch.sh /home/${USER}/experiments/

WORKDIR /home/${USER}/experiments
RUN make exp-exchange

ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

USER ${USER}

#CMD ./launch.sh
CMD ["/usr/sbin/sshd", "-D"]
